### ISSUE TITLE
Kartik DataPicker doesnt work

### ISSUE THREAD

**Issue by jb-studio** [wbraganca/yii2-dynamicform#96]
Hi!
Is it possible to use Kartik DataPicker with this extension?
For some reasons DatePicker only works on first field
When I adding others DatePicker fields they are not functional

**Comment by jonatasfl** [comment]
Try this https://github.com/wbraganca/yii2-dynamicform/pull/95/files

**Comment by jb-studio** [comment]
jonatasfl thanks for help
I changed files but it still doesn't work ((
only first field with DatePicker working ((

**Comment by jb-studio** [comment]
I have this error message
Uncaught TypeError: Cannot read property 'widgetItem' of undefined

**Comment by jb-studio** [comment]
When I need input field I am using this code
<?= $form->field($modelAddress, "[{$i}]full_name")->textInput(['maxlength' => true]) ?>
attribute = "[{$i}]full_name"

What code I have to use if I need DatePicker?
I am using this one

<?=$form->field($modelExpiryDates, 'expiry_date')->widget(DatePicker::classname(), [
     'options' => ['placeholder' => 'Enter birth date ...'],
     'removeButton' => false,
 ]);

How to put correct attribute?
Correct one should be '[{$i}]expiry_date' or just 'expiry_date'?
If I use '[{$i}]expiry_date' I do have a error
Uncaught Error: Syntax error, unrecognized expression: #productsexpirydates-{$i}-expiry_date-kvdate

**Comment by jb-studio** [comment]
Problem is fixed now ;)
Thanks jonatasfl

**Comment by danieltang3434** [comment]
Can I know what is your exact solution?
I followed this link: https://github.com/wbraganca/yii2-dynamicform/pull/95/files
and make changes on my files but the date picker for 2nd form and above still not shows up.
I would be nice if you can show me step by step instruction.
Thank you in advance.
